# Generated by Django 6.0.3 on 2026-04-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_integrationcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverify',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
