# Generated by Django 6.0.3 on 2026-04-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0010_profile_city_profile_country_profile_postal_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='address_line1',
            new_name='address',
        ),
    ]
