# Generated by Django 6.0.3 on 2026-04-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0011_rename_address_line1_deliveryaddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
