# Generated by Django 6.0.3 on 2026-07-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
