services:
  web:
    build: .
    container_name: drf_app
    env_file:
      - .env
    environment:
      - APP_PORT=${APP_PORT:-8000}
      - DJANGO_PORT=${APP_PORT:-8000}
      - DB_HOST=${DATABASE_URL}
      - REDIS_HOST=redis
      - QUERY_PRODUCTS_DOMAIN=${QUERY_PRODUCTS_DOMAIN}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    command: >
      sh -c "python manage.py migrate &&
             python create_superuser.py &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:${APP_PORT}"
    volumes:
      - .:/app
    depends_on:
      # - db
      - redis
    networks:
      - shared-network
      - app-network

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - app-network

networks:
  shared-network:
    external: true
  app-network:
    driver: bridge
