# Generated by Django 6.0.3 on 2026-03-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_remove_order_address'),
        ('users_app', '0007_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users_app.deliveryaddress'),
        ),
    ]
