# Generated by Django 6.0.3 on 2026-03-31 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
    ]
