# Generated by Django 6.0.3 on 2026-03-31 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_remove_orderitem_variant'),
        ('products_app', '0004_rename_selling_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products_app.product'),
        ),
    ]
