# Generated by Django 6.0.3 on 2026-04-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0006_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('delivering', 'Delivering'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('out_for_delivery', 'Out for Delivery')], db_index=True, default='delivering', max_length=30),
        ),
    ]
