# Generated by Django 6.0.3 on 2026-04-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0007_alter_shipment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
