# Generated by Django 6.0.3 on 2026-04-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0008_delete_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='line_total',
            new_name='total',
        ),
    ]
