# Generated by Django 6.0.3 on 2026-04-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0009_rename_line_total_orderitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sku',
        ),
    ]
