# Generated by Django 6.0.3 on 2026-04-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0011_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('same_day', 'Same Day')], default='standard', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_days_min', models.PositiveIntegerField()),
                ('estimated_days_max', models.PositiveIntegerField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='shipment_icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'price'],
            },
        ),
    ]
