# Generated by Django 6.0.3 on 2026-04-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0012_shipmentsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentsetting',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveField(
            model_name='shipmentsetting',
            name='price',
        ),
    ]
