# Generated by Django 6.0.3 on 2026-04-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0013_alter_shipmentsetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentsetting',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
