# Generated by Django 6.0.3 on 2026-06-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0016_alter_shipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
