# Generated by Django 6.0.3 on 2026-06-16 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0018_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='track_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
