# Generated by Django 6.0.3 on 2026-06-16 12:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0019_order_order_number_order_track_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, help_text='6-digit order number (e.g., 784912)', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='track_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal tracking UUID', unique=True),
        ),
    ]
