# Generated by Django 6.0.3 on 2026-06-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0020_alter_order_options_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='track_id',
        ),
    ]
