# Generated by Django 6.0.3 on 2026-06-16 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0021_remove_order_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders_app.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders_app.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders_app.order'),
        ),
        migrations.AlterField(
            model_name='shipmentsetting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
