# Generated by Django 6.0.3 on 2026-07-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0022_payment_order_shipment_order_supportticket_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
