# Generated by Django 6.0.3 on 2026-07-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0025_order_coupon_code_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Update Tech Dropshipping', max_length=255)),
                ('contact_email', models.EmailField(default='support@updatetech.com', max_length=254)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_assets/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_assets/')),
                ('bkash_app_key', models.CharField(default='bksh_app_key_82910391', max_length=255)),
                ('bkash_app_secret', models.CharField(default='••••••••••••••••••••••••••••••••', max_length=255)),
                ('nagad_merchant_id', models.CharField(default='nagad_m_90192', max_length=255)),
                ('smtp_domain', models.CharField(default='mail.updatetech.com', max_length=255)),
                ('sms_api_token', models.CharField(default='sms_auth_tok_•••••••', max_length=255)),
                ('whatsapp_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
