# Generated by Django 6.0.3 on 2026-08-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0026_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='shipping_charge_air',
            field=models.DecimalField(decimal_places=2, default=780.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='shipping_charge_sea',
            field=models.DecimalField(decimal_places=2, default=170.0, max_digits=10),
        ),
    ]
