# Generated by Django 6.0.3 on 2026-03-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='sort_order',
        ),
    ]
