# Generated by Django 6.0.3 on 2026-03-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_product_selling_price_alter_product_base_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='price',
        ),
    ]
