# Generated by Django 6.0.3 on 2026-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_settingexchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('search_item', models.CharField(blank=True, max_length=100)),
                ('filter_schema', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('parent', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
