# Generated by Django 6.0.3 on 2026-07-12 12:44

from django.db import migrations, models


def populate_suggestions(apps, schema_editor):
    SearchSuggestion = apps.get_model('products_app', 'SearchSuggestion')
    keywords = [
        "adult hat", "Fashion Accessories & Jewelry", "Necklace", "Bracelet", "ring", "Hairpin", "sunglasses", "Ear studs", "quartz watch", "earrings",
        "Belt", "Frame glasses", "bracelet", "Pendant", "adult gloves", "hair tie", "Headband", "glasses case", "scarf", "Brooch",
        "Silk scarf", "Jewelry set", "Display rack", "Mechanical watch", "Hair band", "Dance Accessories", "Sun protection sleeves", "Reading glasses",
        "ladies shoulder bag", "Ladies Crossbody Bag", "lady's handbag", "Travel bag", "Travel suitcase", "leisure backpack", "backpack", "Tote Bag",
        "ladies' backpack", "makeup bag", "Primary school backpack", "lady's wallet", "Men's crossbody bag", "small square bag", "Card pack", "Men's wallet",
        "Business Backpack", "Change purse", "Men's Chest Bag", "Underarm bag", "Kindergarten schoolbag", "Men's single shoulder bag", "sports backpack",
        "Sports waist bag", "Phone pouch", "Bucket bag", "student schoolbag", "toolkit", "Computer bag", "Document holder",
        "Dress", "Women's T-shirt", "Casual Suit", "Casual Pants", "Half skirt", "Women's shirt", "Women's jeans", "Women's knitted sweater",
        "Women's hoodie", "Sweater", "little suit", "stage costumes", "women's vest", "Ladies' shorts", "Ladies' sun protection clothing", "Cotton coat",
        "Women's Jumpsuit", "Maternity pants", "wedding dress", "Chiffon blouse", "woolen coat", "Down jacket", "Cosplay costume", "Plus size dress",
        "Women's jacket", "Evening gown", "Women's windbreaker", "cheongsam", "ladies' leather jacket", "Plus size T-shirt",
        "Men's T-shirt", "Men's casual pants", "Men's jeans", "Men's hoodie", "Men's shirt", "Men's jacket", "Men's Polo Shirt", "Men's casual sport suit",
        "Men's casual shorts", "Men's knitted sweater", "Men's trousers", "Men's cotton jacket", "Men's vest", "Men's casual vest", "Men's beach pants",
        "Men's PU Leather Jacket", "Men's suit set", "Mens down jacket", "Men's denim shorts", "Men's Sun Protection Clothing", "National Costume",
        "Mens sweatpants", "Men's casual suit", "Men's trench coat", "men's overcoat", "Men's cotton vest", "Men's baseball jacket", "Men's wool sweater",
        "Men's cosplay costume", "Men's genuine leather jacket",
        "Kids Set", "Kids pants", "Kids dress", "Kids T-shirt", "Kids Pajamas", "Kids socks", "Kids sandals", "Kids underwear", "Kids hat",
        "Kids sports shoes", "baby walking shoes", "children's shirt", "Children's hair accessories", "Children's outerwear", "Kids leather shoes",
        "Kids slippers", "Children's jeans", "Children's half skirt", "Children's performance costume", "Children's formal wear", "Children's vest",
        "Kids canvas shoes", "children's sweater", "Kids Hoodie", "Kids Backpack", "Children's shoulder bag", "Kids leggings", "Parent-child matching outfits",
        "Children's clogs",
        "Women's Loungewear", "Ladies' triangle briefs", "Sports cotton socks", "Seductive Lingerie Set", "Little vest", "Seamless Bra", "Boxer shorts",
        "Wireless bra", "sleepwear", "Chest binding", "shaping pants", "ladies' vest", "Boat socks", "Seductive sleepwear", "leggings", "Body shaping top",
        "Bra set", "Bras for teenage girls", "Waist trainer", "Chest sticker", "Shaping bra", "Body shaping suit", "Sleeping gown", "home pants",
        "stockings", "Tights", "Couple Home Wear", "nursing bra", "Lady's G-string", "Thick cozy socks",
        "Women's casual single shoes", "Flat slippers", "Men's sports shoes", "Fashion single shoes", "Women's sports shoes", "EVA slippers",
        "Men's leather shoes", "Ladies' sandals", "High heels", "Canvas shoes", "Rain boots", "Women's boots", "Loafers", "sports sandals", "Hole shoes",
        "Wedding shoes", "Work shoes", "Martens boots", "Men's boots", "Women's leather shoes", "Cotton slippers", "Chelsea boots", "pointed toe shoes",
        "Men's sandals", "Dance shoes", "Roman sandals", "Functional shoes", "Snow boots", "moccasins", "safety shoes",
        "Yoga mat", "yoga suit", "Dumbbell", "Jump rope", "Yoga block", "resistance band", "Grip strength", "Fitness equipment", "treadmill", "Yoga ball",
        "Abdominal wheel", "Yoga pants", "fascia gun", "Sports bra", "hula hoop", "fitness ball", "Gym equipment", "Fitness gloves", "Tensioner",
        "Yoga towel", "foam roller", "Push-up rack", "Yoga straps", "pilates equipment", "Fitness tracker", "massage ball", "Yoga wheel", "Stepper",
        "Weight bench", "Bodybuilding supplement",
        "Outdoor tent", "Sleeping bag", "Picnic mat", "outdoor backpack", "Camping light", "Folding chair", "climbing gear", "Outdoor tableware",
        "binoculars", "Outdoor clothing", "Compass", "Flashlight", "Trekking poles", "Hydration pack", "Outdoor stove", "Survival kit", "Outdoor watch",
        "Hammock", "Beach umbrella", "Sun protection hat", "Sunglasses", "Waterproof bag", "Outdoor blanket", "Grill", "Camping tool", "Lantern", "Rope",
        "Raincoat", "First aid kit", "Insect repellent",
        "Bicycle Decoration", "scooter", "Bicycle Light", "Cycling mask", "cycling gloves", "Bicycle Helmet", "Cycling uniform", "bicycle tire",
        "bicycle bag", "bicycle repair tools", "Mountain bike", "Heelys shoes", "roller skating", "saddle", "Cycling Backpack", "Self-balancing scooter",
        "cycling shoes", "foot pedal", "children's vehicle", "skateboard", "crankshaft", "vehicle axle", "foldable bike", "Bicycle Odometer",
        "cycling arm warmers", "chain", "bicycle", "flywheel", "Bicycle bell", "car brake",
        "football uniform", "Racket handle grip", "badminton racket", "football", "pickleball paddle", "basketball uniform", "badminton",
        "Football training equipment", "football goal", "badminton uniform", "badminton bag", "basketball hoop", "Pickleball", "table tennis racket",
        "basketball", "table tennis", "net", "Goalkeeper gloves", "tennis bag", "Basketball bag", "Football shin guard", "Football socks", "tennis",
        "Badminton net", "fan merchandise", "training vest", "baseball", "volleyball", "table tennis racket rubber", "Badminton racket string",
        "fishing bait", "swimming pool", "fishing reel", "fishing rod", "Golf Accessories", "Archery equipment", "fishing line", "poker",
        "Video game equipment", "Billiard accessories", "combined slide", "Fishing hook", "Kids Naughty Castle", "chips", "fishing float", "mahjong",
        "fishing bag", "fishing boat", "billiard table", "Fishing and Conservation", "golf bag", "chess set", "Water Amusement Facilities",
        "bumper cars", "Golf clothing", "billiard cue", "Fish Finder", "fishing box", "fishing sinkers", "fishing rod stand",
        "Knee Pads", "Dry Bag", "Protective Gear", "Lumbar Support", "Swim Goggles", "Wrist Guard", "Sport Cap", "Cycling Glasses", "Hand Guard",
        "Ankle Support", "Cooling Sleeves", "Elbow Pads", "Leg Guards", "Shoulder Support", "Fitness Tracker", "Sports headband", "Exercise Mat",
        "Whistle", "Rain Cover", "Head Protector", "Sports Glasses", "Scoreboard", "Stopwatch", "Ballistic Glasses", "Ski Goggles",
        "Display rack", "billboard", "sports track", "display cabinet", "light box", "Exhibition tent", "advertising machine", "Advertising flagpole",
        "inflatable model", "stadium seat", "artificial turf", "Trophy", "Medal", "Banner", "Post",
        "Mobile Phone Case", "Data cable", "Tempered film", "Charger", "Mobile Phone Stand", "Power Bank", "Memory card", "USB flash drive",
        "Mobile Phone Battery", "Headphones", "Bluetooth headset", "Screen assembly", "Repair tool", "Protection film", "Stylus",
        "Laptop", "Mouse", "Keyboard", "Monitor", "Printer", "Scanner", "Router", "Projector", "External hard drive", "Computer components",
        "Cookware", "Tableware", "Kitchen tools", "Bakeware", "Dinnerware",
        "Wall art", "Candles", "Vases", "Clocks", "Mirrors",
        "Lipstick", "Foundation", "Mascara", "Eye shadow", "Makeup brushes",
        "Moisturizer", "Cleanser", "Sunscreen", "Serum", "Face mask",
        "Plush toys", "Action figures", "Dolls", "Puppets",
        "Jigsaw puzzles", "Board games", "Card games", "Educational toys",
        "First aid kits", "Masks", "Thermometers", "Blood pressure monitors",
        "Massagers", "Hearing aids", "Braces & supports",
        "Engine parts", "Braking system", "Car electronics", "Auto lighting",
        "Car covers", "Seat covers", "Car mats", "Navigation system",
        "Food processing machinery", "Packaging machines", "Woodworking machinery",
        "Conveyors", "Forklifts", "Lifting equipment",
        "beach buggy", "electric bicycle", "Electric tricycle", "electric motorcycle", "Electric scooter", "electric mobility scooter"
    ]
    unique_keywords = list(set([k.strip() for k in keywords if k and k.strip()]))
    suggestions = [SearchSuggestion(keyword=kw) for kw in unique_keywords]
    SearchSuggestion.objects.bulk_create(suggestions)


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0008_category_subcategory_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
        migrations.RunPython(populate_suggestions),
    ]
