# Generated by Django 6.0.3 on 2026-03-31 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_alter_cartitem_options_and_more'),
        ('products_app', '0003_product_selling_price_alter_product_base_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
