# Generated by Django 6.0.3 on 2026-03-31 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_user_cart',
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_session_cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
