# Generated by Django 6.0.3 on 2026-04-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
