# Generated by Django 6.0.3 on 2026-04-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
