# Generated by Django 6.0.3 on 2026-04-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_cartitem_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
