# Generated by Django 6.0.3 on 2026-04-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0008_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
