# Generated by Django 6.0.3 on 2026-04-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0009_cartitem_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
    ]
