# Generated by Django 6.0.3 on 2026-04-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0011_alter_cartitem_unique_together_cartitem_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
