# Generated by Django 6.0.3 on 2026-04-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0012_remove_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.JSONField(default=1),
        ),
    ]
