# Generated by Django 6.0.3 on 2026-04-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0013_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_id')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant_key',
        ),
    ]
