# Generated by Django 6.0.3 on 2026-06-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0015_cartvariant_cartvariantsize_newcartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartvariantsize',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='newcartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartVariant',
        ),
        migrations.DeleteModel(
            name='CartVariantSize',
        ),
        migrations.DeleteModel(
            name='NewCartItem',
        ),
    ]
