# Generated by Django 6.0.3 on 2026-06-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0016_remove_cartvariantsize_variant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
