# Generated by Django 6.0.3 on 2026-06-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0017_delete_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
